### PR TITLE
Add missing "do not disturb" param

### PR DESCRIPTION
**Pull request by rozwell**
Since it's a basic functionality now, I think it should be enabled unless there's a reason not to?

### CODE REVIEW

**Comment by Jajcus** [comment]
Is this enough? Shouldn't jggtrans also translate XMPP <show>dnd</show> to/from the appropriate GG code?

**Comment by rozwell** [comment]
Seems to be. After adding this parameter, dnd works just fine (for few months already).

**Comment by rozwell** [comment]
Sry, closed accidentally.

**Comment by Jajcus** [comment]
Thanks :)

**Pull request merged**
